name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    name: UI Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://automationexercise.com/
      API_URL: https://automationexercise.com/api
      NODE_ENV: dev
      HEADLESS: true
      WORKERS: 1

      USER_NAME: ${{ secrets.USER_NAME }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run UI tests
        run: npm run uitests

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-ui
          path: allure-results
          retention-days: 14  


  api-tests:
    name: API Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://automationexercise.com/
      API_URL: https://automationexercise.com/api
      NODE_ENV: dev
      HEADLESS: true
      WORKERS: 1

      USER_NAME: ${{ secrets.USER_NAME }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run API tests
        run: npm run apitests

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: allure-results
          retention-days: 14  


  network-tests:
    name: Network Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://automationexercise.com/
      API_URL: https://automationexercise.com/api
      NODE_ENV: dev
      HEADLESS: true
      WORKERS: 1

      USER_NAME: ${{ secrets.USER_NAME }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Network tests
        run: npm run networktests

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-network
          path: allure-results
          retention-days: 14  